### ISSUE TITLE
converstion issue

### ISSUE THREAD

**Issue by eubersen** [hoxnox/string#1]
I have the following function using codecvt_cp1251:

std::string ws2s(const std::wstring& wstr)
{
    std::wstring_convert<codecvt_cp1251, wchar_t> converterX;
    return converterX.to_bytes(wstr);
}

I tried to convert L"192.168.12.95" from unicode to cp1251. As the result this function returns "192.168.2.95". The 9th symbol ('1') is missed.

**Comment by hoxnox** [comment]
Thanks for the report, but unfortunately I can't reproduce the problem. What platform do you use? On gentoo x86_64 gcc-4.8.4 I've got the following:

code sample:

```
#include <iostream>
#include <locale>
#include <facet/codecvt/codecvt_cp1251.hpp>
#include <string.hpp>

int
main(int argc, char* argv[])
{
    nx::String s = L"192.168.12.95";
    std::cout << s.toCP1251() << std::endl;
    return 0;
}
```

the output:

```
$>./a.out 192.168.12.95
192.168.12.95
```

**Comment by eubersen** [comment]
I've got ьн result at MS VisualStudio 2013. The issue was in this part of code:
      if(to == to_end)
      {
        from_next = ++from;
        to_next = to;
        return partial;
      }

if change it to

```
  if(to == to_end)
  {
    from_next = from;
    to_next = to;
    return partial;
  }
```

than everything is ok

**Comment by hoxnox** [comment]
I hope this fix won't be a reason of infinite loop some day... =)
